# Generated by Django 5.2.8 on 2025-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الصنف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('unit', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('reference_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر المرجعي')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
            },
        ),
    ]
