# Generated by Django 5.2.8 on 2025-11-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices_app', '0001_initial'),
        ('receipts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('match', 'مطابق'), ('missing', 'ناقص'), ('extra', 'صنف زائد')], max_length=10, verbose_name='حالة المطابقة')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الفرق في الكمية')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices_app.invoiceitem', verbose_name='بند الفاتورة')),
                ('receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipts_app.receiptitem', verbose_name='بند الاستلام')),
            ],
            options={
                'verbose_name': 'نتيجة مطابقة',
                'verbose_name_plural': 'نتائج المطابقة',
            },
        ),
    ]
